name: mask_for_camera_view
description: Crop section image from camera
version: 1.3.1
homepage: 'https://github.com/turoboff/mask_for_camera_view'

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.12
  camera: ^0.10.3
  dotted_border: ^2.0.0+3

#dependency_overrides:
#  camera_android:
#    git:
#      url: https://github.com/OmarHatem28/plugins.git
#      path: packages/camera/camera_android
#      ref: 8550e0e698f3d358f42d60b090320dea7c3c0775

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.mask_for_camera_view
        pluginClass: MaskForCameraViewPlugin
      ios:
        pluginClass: MaskForCameraViewPlugin
